import { pool } from '../db.js';

export const databaseService = {
    async createSession(data: { symbol: string, type: string, strategyId: string }) {
        // 1. Validate Strategy Exists & Matches Symbol
        // We join strategies to get the symbol and user_id.
        const strategyRes = await pool.query(
            `SELECT id, symbol, user_id FROM strategies WHERE id = $1`,
            [data.strategyId]
        );

        if (strategyRes.rows.length === 0) {
            console.warn(`[DB] Strategy ${data.strategyId} not found.`);
            throw new Error(`Strategy ${data.strategyId} not found`);
        }

        const strategy = strategyRes.rows[0];

        // 2. Create Session
        // UUIDs are generated by DB default (uuid_generate_v4())
        // REQUIRED: user_id (fetched from strategy owner)
        const insertRes = await pool.query(
            `INSERT INTO sessions (strategy_id, user_id, mode, status, started_at)
             VALUES ($1, $2, $3, $4, NOW())
             RETURNING id, strategy_id, status, started_at`,
            [data.strategyId, strategy.user_id, 'LIVE', 'RUNNING']
        );

        const session = insertRes.rows[0];
        console.log(`[DB] Created Session: ${session.id} for ${strategy.symbol}`);

        return {
            id: session.id,
            symbol: strategy.symbol,
            type: 'stock', // Defaulting as before
            strategyId: session.strategy_id,
            status: session.status,
            createdAt: session.started_at
        };
    },

    // this is for individual session stops 
    async stopSession(sessionId: string) {
        try {
            // Update and Return, joining with strategies to get symbol back for the UI return object
            const res = await pool.query(
                `WITH updated_session AS (
                    UPDATE sessions
                    SET status = 'STOPPED', ended_at = NOW()
                    WHERE id = $1
                    RETURNING id, strategy_id, status, started_at
                 )
                 SELECT s.id, s.strategy_id, s.status, s.started_at, st.symbol
                 FROM updated_session s
                 JOIN strategies st ON s.strategy_id = st.id`,
                [sessionId]
            );

            if (res.rows.length === 0) {
                return null;
            }

            const session = res.rows[0];
            console.log(`[DB] Stopped Session: ${sessionId}`);

            return {
                id: session.id,
                symbol: session.symbol,
                type: 'stock',
                strategyId: session.strategy_id,
                status: session.status, // Should be STOPPED
                createdAt: session.started_at
            };
        } catch (error) {
            console.error(`[DB] Failed to stop session ${sessionId}:`, error);
            return null;
        }
    },

    async hasActiveSessionsForSymbol(symbol: string): Promise<boolean> {
        const res = await pool.query(
            `SELECT COUNT(*) 
             FROM sessions s
             JOIN strategies st ON s.strategy_id = st.id
             WHERE s.status = 'RUNNING' AND st.symbol = $1`,
            [symbol]
        );
        return parseInt(res.rows[0].count) > 0;
    },

    // this is for multiple session stops (when a strategy is deleted)  
    async stopStrategySessions(strategyId: string) {
        try {
            // Update all running sessions for a strategy and return their IDs
            const res = await pool.query(
                `WITH updated_sessions AS (
                    UPDATE sessions
                    SET status = 'STOPPED', ended_at = NOW()
                    WHERE strategy_id = $1 AND status = 'RUNNING'
                    RETURNING id
                 )
                 SELECT us.id as session_id, 
                        (SELECT symbol FROM strategies WHERE id = $1) as symbol
                 FROM updated_sessions us`,
                [strategyId]
            );

            // Extract session IDs and symbol
            const sessionIds = res.rows.map(r => r.session_id);
            const symbol = res.rows.length > 0 ? res.rows[0].symbol : null;

            return {
                symbol,
                sessionIds,
                count: sessionIds.length
            };
        } catch (error) {
            console.error(`[DB] Failed to stop sessions for strategy ${strategyId}:`, error);
            throw error;
        }
    }
};
